### PR TITLE
Switch to yarn 3

### PR DESCRIPTION
**Pull request by svix-liam**

### CODE REVIEW

**Comment by tasn** [comment]
What's the reason for the change? Also, are we sure it'll not break docusaurus?

**Comment by svix-liam** [comment]
Since I have yarn3 installed locally, every time I switch to the docs repo locally, I need to regenerate the yarn.lock file, remember not to commit the change to my branch, then revert the change when switching branches. It's getting pretty tedious.

---

I've been using it locally ever since we switched to yarn3 in the monorepo and it works fine.

**Comment by tasn** [comment]
How will it affect people not using yarn3? Will it cause any issues?

**Comment by tasn** [comment]
OK, so feel free to mrege.

**Pull request merged**
